
#type: args

train:
  feats: 80
  epochs: 400
  val_interval: 5
  batch_size: 96 
  use_ema: true

  lr_scheduler:
    use: true
    type: "StepLR"
    step_size: 150
    gamma: 0.1
    verbose: true
    
  optimizer:
    type: "Adam"
    lr: 1.0e-3
    weight_decay: 0.
    
diffusion:
  beta_start: 0.0001
  
  beta_end: 0.5
  num_steps: 50
  schedule: "quad"

test:
  batch_size: 64